### ISSUE TITLE
Source in the repo is outdated

### ISSUE THREAD

**Issue by ecm-pushbx** [abergs/tabstospaces#2]
The source in this repo, which is at https://github.com/abergs/tabstospaces/blob/102b6ef40bfaea57a4980d93df62f47ba06aeb70/TabsToSpaces/index.html seems to be outdated. It doesn't contain the selection of tab width and always seems to expand to four tabs. This part, for example, is missing:

```
<select id="numSpaces">
<option value="1">1 space</option>
<option value="2">2 spaces</option>
<option value="4" selected="selected">4 spaces</option>
</select>
```

**Comment by abergs** [comment]
Up-to-date code is in gh-pages branch
