### ISSUE TITLE
No usage conditions or license specified

### ISSUE THREAD

**Issue by ecm-pushbx** [abergs/tabstospaces#3]
I can't find any usage conditions in this repo or in the source of the live website.

**Comment by ecm-pushbx** [comment]
Personally I'd recommend https://opensource.org/licenses/Fair which in full reads:

> Usage of the works is permitted provided that this
> instrument is retained with the works, so that any entity
> that uses the works is notified of this instrument.
>
> DISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.

**Comment by abergs** [comment]
Done
